name = "new-cf-ai-backend"
main = "src/index.ts"
compatibility_date = "2024-02-23"
node_compat = true

# [env.preview]
# [[vectorize]]
# binding = "VECTORIZE_INDEX"
# index_name = "supermem-vector-dev"

# [[vectorize]]
# binding = "VECTORIZE_INDEX"
# index_name = "supermem-vector-prod"

[ai]
binding = "AI"

# [[queues.producers]]
#  queue = "batch-vector-queue"
#  binding = "MY_QUEUE"

#  [[queues.consumers]]
#  queue = "batch-vector-queue"

[[kv_namespaces]]
binding = "KV"
my_id="920cce6847dd4d489a6948559dede348"
id = "920cce6847dd4d489a6948559dede348"
preview_id = "c58b6202814f4224acea97627d0c18aa"

[placement]
mode = "smart"
